### ISSUE TITLE
"ValueError: Correlation matrix is not symmetric. This should not occur and is probably caused by an overflow error or too low dtype precision."

### ISSUE THREAD

**Issue by austinweigle** [moldyn/MoSAIC#21]
I have installed MoSAIC into a python 3.8 environment, and have run the following command:

`python -m mosaic similarity -i test.dat -o output_similarity --metric correlation -v`

My output looks like this:

`MoSAIC SIMILARITY
~~~ Initialize similarity class
~~~ Load file test.dat
~~~ Fit input.
/home/austin/miniconda3/envs/mosaic/lib/python3.8/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/austin/miniconda3/envs/mosaic/lib/python3.8/site-packages/numpy/lib/function_base.py:2855: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Traceback (most recent call last):
  File "/home/austin/miniconda3/envs/mosaic/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/austin/miniconda3/envs/mosaic/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/austin/miniconda3/envs/mosaic/lib/python3.8/site-packages/mosaic/__main__.py", line 363, in <module>
    main()
  File "/home/austin/miniconda3/envs/mosaic/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/austin/miniconda3/envs/mosaic/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/austin/miniconda3/envs/mosaic/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/austin/miniconda3/envs/mosaic/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/austin/miniconda3/envs/mosaic/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/austin/miniconda3/envs/mosaic/lib/python3.8/site-packages/mosaic/__main__.py", line 153, in similarity
    sim.fit(X)
  File "/home/austin/miniconda3/envs/mosaic/lib/python3.8/functools.py", line 912, in _method
    return method.__get__(obj, cls)(*args, **kwargs)
  File "/home/austin/miniconda3/envs/mosaic/lib/python3.8/site-packages/mosaic/similarity.py", line 208, in _
    corr = _correlation(X)
  File "<@beartype(mosaic._correlation_utils._correlation) at 0x7fdb541b9d30>", line 50, in _correlation
  File "/home/austin/miniconda3/envs/mosaic/lib/python3.8/site-packages/mosaic/_correlation_utils.py", line 109, in _correlation
    raise ValueError(
ValueError: Correlation matrix is not symmetric. This should not occur and is probably caused by an overflow error or too low dtype precision.`

I have tried changing the shape of my input `test.dat`, but the result is always the same. I convert my npy file to dat format using a command like this:
`np.savetxt('test.dat', npy_array, fmt='%.4f')`

I am not sure how I can circumvent this issue. I would like to use MoSAIC to reduce my feature set from 2070 to something more reasonable. There is no tutorial file available for determining similarity; the only example file that I see is `MoSAIC/example/toy_matrix_paper`, which is meant for testing the MoSAIC clustering function rather than the MoSAIC similarity function.

Let me know if there is anything else I can do or provide input files.

Thanks,
Austin

**Comment by austinweigle** [comment]
Hi gegabo,

Thanks for the reply!

I am testing out the MoSAIC functions with a single 1 µs trajectory. The 1 µs trajectory is 5000 frames. I currently have 2070 features that I am interested in reducing through your correlation and clustering approaches to help with discretization for an MSM. My ultimate goal is to be able to provide a larger dataset like you did in your paper (for me ~30-60 µs) so that I can see how the features correlate/cluster throughout my current sampling of phase space. Straight from my test trajectory, the npy/dat file dimensions are [5000, 2070]. I have tried reducing the file in size to [2070, 2070], [1000,2070], [500, 2070], and [100, 2070]. But I still got the same error.

Unfortunately, trying it in python did not work. When attempting the python snippet I converted the npy file to `astype(np.double)`, but I still got the same error. The same thing happened when I tried to use the mosaic command in terminal after increasing the `--precision` parameter to 'double'.

I also tried using any other similarity methods that is different from correlation. In all cases I ultimately got this error:

```
MoSAIC SIMILARITY
~~~ Initialize similarity class
~~~ Load file test.dat
~~~ Fit input.
/home/austin/miniconda3/envs/mosaic/lib/python3.8/site-packages/mosaic/_correlation_utils.py:47: RuntimeWarning: invalid value encountered in scalar divide
  np.ceil(ptp / binwidth),
Traceback (most recent call last):
  File "/home/austin/miniconda3/envs/mosaic/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/austin/miniconda3/envs/mosaic/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/austin/miniconda3/envs/mosaic/lib/python3.8/site-packages/mosaic/__main__.py", line 363, in <module>
    main()
  File "/home/austin/miniconda3/envs/mosaic/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/austin/miniconda3/envs/mosaic/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/austin/miniconda3/envs/mosaic/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/austin/miniconda3/envs/mosaic/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/austin/miniconda3/envs/mosaic/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/austin/miniconda3/envs/mosaic/lib/python3.8/site-packages/mosaic/__main__.py", line 153, in similarity
    sim.fit(X)
  File "/home/austin/miniconda3/envs/mosaic/lib/python3.8/functools.py", line 912, in _method
    return method.__get__(obj, cls)(*args, **kwargs)
  File "/home/austin/miniconda3/envs/mosaic/lib/python3.8/site-packages/mosaic/similarity.py", line 213, in _
    matrix_ = self._nonlinear_correlation(X)
  File "<@beartype(mosaic.similarity.Similarity._nonlinear_correlation) at 0x7f31e3a7e940>", line 50, in _nonlinear_correlation
  File "/home/austin/miniconda3/envs/mosaic/lib/python3.8/site-packages/mosaic/similarity.py", line 307, in _nonlinear_correlation
    nl_corr_ij = calc_nl_corr(*_estimate_densities(xi, xj))
  File "<@beartype(mosaic._correlation_utils._estimate_densities) at 0x7f31e3a71af0>", line 117, in _estimate_densities
  File "/home/austin/miniconda3/envs/mosaic/lib/python3.8/site-packages/mosaic/_correlation_utils.py", line 78, in _estimate_densities
    _freedman_diaconis_rule(y),
  File "<@beartype(mosaic._correlation_utils._freedman_diaconis_rule) at 0x7f31e3f19c10>", line 49, in _freedman_diaconis_rule
  File "/home/austin/miniconda3/envs/mosaic/lib/python3.8/site-packages/mosaic/_correlation_utils.py", line 46, in _freedman_diaconis_rule
    return int(
ValueError: cannot convert float NaN to integer
```

Tracing the errors, it looks like there is an issue with my data when `_correlation_utils.py` tries to perform the `_freedman_diaconis_rule` function on my input data such that it cannot return the `int(np.ceil(ptp / bandwidth)`.

I am not familiar with the math for this function, but I do know that I do not have any inherent NaNs within my input file. 

When I try using the --low-memory flag, I get this error:

```
MoSAIC SIMILARITY
~~~ Initialize similarity class
~~~ Fit on-the-fly test_2070.dat
/home/austin/miniconda3/envs/mosaic/lib/python3.8/site-packages/mosaic/_correlation_utils.py:279: RuntimeWarning: invalid value encountered in divide
  corr = corr / (n_samples - 1) / (
~~~ Store similarity matrix in output_similarity
```

I have attached a [2070, 2070] shaped object from my test trajectory.
[test_2070_dat.tar.gz](https://github.com/moldyn/MoSAIC/files/11123710/test_2070_dat.tar.gz)

Perhaps it is just possible that MoSAIC cannot test as many features per frame as I am providing?

Thanks again for your help. I really liked the message you sent in your JCTC paper because it is true; often times deciding upon an initial feature set for further dimensionality reduction is sort of a "chicken or the egg" problem. I would love to be able to use MoSAIC in my project for that exact purpose.

Cheers,
Austin

**Comment by austinweigle** [comment]
Thanks Georg,

Yeah, I noticed from some troubleshooting last week that I was able to check what was being passed throughout the `_freedman_diaconis_rule` function. I also saw that there was an array of 2070 values with 0.0, but I was not sure if that was from some type of artificial padding or not. Now understanding that your method takes each column from each frame, then yes this mistake is on my end. Thank you so much for helping me with this! I am excited to see what results CPM yields :) 

Austin

**Comment by gegabo** [comment]
Great! If you have any more questions, feel free to contact again. Wishing you success with your MSM!
